stages:
  - build
  - deploy

image: hashicorp/terraform

stages:
  - validate
  - build 
  - gettools
before_script:
  - alias convert_report="jq -r '([.resource_changes[]?.change.actions?]|flatten)|{\"create\":(map(select(.==\"create\"))|length),\"update\":(map(select(.==\"update\"))|length),\"delete\":(map(select(.==\"delete\"))|length)}'"
  - terraform --version
  - terraform init -var-file=modules/private-tls-cert/variables.tf
  # - apt update && apt install  --assume-yes git wget unzip
  # - git config --global http.sslVerify false 
  

