stages:
  - build
  - deploy

image: ubuntu:18.04


build:
  stage: build 
  script: 
    - packer version
  when: manual

get_packer:
  stage: build 
  when: manual
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - packer
  script:
    - echo "hi"
  
