stages:
  - build
  - deploy

image: registry.gitlab.com/gitlab-org/gitlab-build-images:terraform

stages:
  - build 
  - gettools
before_script:
  - apt update && apt install  --assume-yes git wget unzip
  - git config --global http.sslVerify false 


get_packer:
  stage: gettools 
  when: manual
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - packer
  script:
    - echo "Download packer"
    - wget https://releases.hashicorp.com/packer/1.5.5/packer_1.5.5_linux_amd64.zip
    - unzip packer_1.5.5_linux_amd64.zip
    - chmod +x packer 

create_tls:
  when: manual
  stage: build
  before_script: []
  script:
    - cd modules/private-tls-cert
    - ls -la
    - terraform init 
    - terraform plan
    - terraform apply

  
build_image:
  stage: build
  when: manual
  script:
    - ./packer  build packerrun.json
