stages:
  - build
  - deploy

image: ubuntu:18.04

before_script:
  - apt update && apt install  --assume-yes git wget unzip
  - git config --global http.sslVerify false 
  
build:
  stage: build 
  script: 
    - packer version
  when: manual

get_packer:
  stage: build 
  when: manual
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - packer
  script:
    - echo "Download packer"
    - wget https://releases.hashicorp.com/packer/1.5.5/packer_1.5.5_linux_amd64.zip
    - unzip packer_1.5.5_linux_amd64.zip
    - chmod +x packer || mv packer /usr/local/bin
    - packer build packerrun.json
  
