stages:
  - build
  - deploy

image: ubuntu:18.04

stages:
  - gettools
  - build 
before_script:
  - apt update && apt install  --assume-yes git wget unzip
  - git config --global http.sslVerify false 
  


get_packer:
  stage: gettools 
  when: always
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - packer
  script:
    - echo "Download packer"
    - wget https://releases.hashicorp.com/packer/1.5.5/packer_1.5.5_linux_amd64.zip
    - unzip packer_1.5.5_linux_amd64.zip
    - chmod +x packer 
  
build_image:
  stage: build
  script:
    - ./packer  build packerrun.json
