stages:
  - build
  - deploy

image: registry.gitlab.com/gitlab-org/gitlab-build-images:terraform

stages:
  - validate
  - build 
  - gettools
before_script:
  - apt update && apt install  --assume-yes git wget unzip
  - git config --global http.sslVerify false 

validate:
  stage: validate
  script:
    - terraform validate

get_packer:
  stage: gettools 
  when: manual
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - packer
  script:
    - echo "Download packer"
    - wget https://releases.hashicorp.com/packer/1.5.5/packer_1.5.5_linux_amd64.zip
    - unzip packer_1.5.5_linux_amd64.zip
    - chmod +x packer 

create_tls:
  when: manual
  stage: build
  before_script:
    - alias convert_report="jq -r '([.resource_changes[]?.change.actions?]|flatten)|{\"create\":(map(select(.==\"create\"))|length),\"update\":(map(select(.==\"update\"))|length),\"delete\":(map(select(.==\"delete\"))|length)}'"
    - terraform --version
    - terraform init
  script:
    - cd modules/private-tls-cert
    - ls -la
    - terraform init 
    - terraform plan
    - terraform apply

    
  
build_image:
  stage: build
  when: manual
  script:
    - ./packer  build packerrun.json
